apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testportal2
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: backstageDoc
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: InstallationGuide
      url: https://backstage.io/docs/getting-started/#1-create-your-backstage-app
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  relations:
    - type: partOf
      target:
        kind: System
        name: dev-portal
    - type: owner
      target:
        kind: Group
        name: team-a
    - type: providesApis
      target:
        kind: API
        name: testportal2-api
  annotations:
    github.com/project-slug: Jhonson924/testportal2
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: other
  lifecycle: development
  owner: jhonson924
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dev-portal
  description: A developer platform system
spec:
  owner: team-a
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: testportal2-api
  description: The public API for testportal2
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition: |
    openapi: 3.0.0
    info:
      title: TestPortal2 API
      version: 1.0.0
    paths: {}

