apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testportal2
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: backstageDoc
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: InstallationGuide
      url: https://backstage.io/docs/getting-started/#1-create-your-backstage-app
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: Jhonson924/testportal2
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: other
  lifecycle: development
  owner: jhonson924
